# Configuración DB
#spring.datasource.url=jdbc:postgresql://localhost:5432/appTFG
spring.datasource.url=jdbc:postgresql://ppscanner_user:pgYmKxp1O6Lfw4fA2UhWRJZgi7g3xQvm@dpg-d7ajgomuk2gs73chgdbg-a/ppscanner
spring.datasource.username=ppscanner_user
spring.datasource.password=pgYmKxp1O6Lfw4fA2UhWRJZgi7g3xQvm
server.address=0.0.0.0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=X9$e!tL7@pQz#Vr2Fh8Wk&G1mBd^o3nJ
jwt.expiration=3600000
